nameTagFormat: "&6&l%name%&6&l's loot"
#leave -1 for no expiry.
graveDuration: 3
#how long 'expired grave' shows for in /grave display
expiredDuration: 3
durationUnit: hours
graveTexture: ewogICJ0aW1lc3RhbXAiIDogMTYyNjk1OTYyNTExOCwKICAicHJvZmlsZUlkIiA6ICI3M2Q0ZTA2ODNhNmQ0YzhiOGY4NTMzMjM1NDY5NTVjNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQ2hlc3QiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzU4MzA1ZTUyN2ZjZjA4NTI1ZmRmZjA3ZTRjZDZlNzk3NzRhY2RkNDI2Y2MyNzMyN2Q0NWRmOGE1ZmY4NjQxOSIKICAgIH0KICB9Cn0=
expiredGraveTexture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmY0ZDhjNTg0NmQ0Y2ZkOGM1ZDE3ZTBhYjBiMDY2NDQxYmRiOGFlMTllNDlkMDkxYWNiYTRlZWI4ZjUyYjlmMCJ9fX0=
onlyOwnersCanLoot: true
doesNotOwnMessage: "&cThis is not your loot!"
invalidGrave: "&7The Grave rots before your eyes."
emptyInv: "&7You died with no loot on you, therefore no grave was created."
deathMsg: "&7A grave was created at your death point at &l%coords%&r&7."