name: EnchantedGraves
version: ${project.version}
main: org.enchantedskies.enchantedgraves.EnchantedGraves
api-version: 1.13
authors: ["Dav_e", "zeddit", "Xemor_"]
commands:
  graves:
    description: The base command of EnchantedGraves
    usage: /graves